version: "3.8"

services:
  netring-member:
    image: harbor.gss.consilio.com/public/library/netring-member:v1.1.8
    container_name: netring-member
    ports:
      - "8758:8758"               # Different port to avoid conflicts
    environment:
      # Member configuration via environment variables (no config file needed!)
      - NETRING_LOCATION=US1
      - NETRING_REGISTRY_URL=https://netring-reg.gss.consilio.com
      - NETRING_POLL_INTERVAL=30
      - NETRING_CHECK_INTERVAL=60
      - NETRING_HEARTBEAT_INTERVAL=45
      - NETRING_TCP_TIMEOUT=5
      - NETRING_HTTP_TIMEOUT=10
      - NETRING_HTTP_ENDPOINTS=/health,/metrics
      - NETRING_SERVER_HOST=0.0.0.0
      - NETRING_SERVER_PORT=8758
      
      # Enhanced testing configuration (new features)
      - NETRING_BANDWIDTH_TEST_INTERVAL=300    # 5 minutes
      - NETRING_TRACEROUTE_INTERVAL=600        # 10 minutes
      - NETRING_BANDWIDTH_TEST_SIZE_MB=1       # 1MB test size
      
      # Auto-detected host IP will be injected here
      - HOST_IP=${HOST_IP}
      
      # Performance and logging
      - PYTHONUNBUFFERED=1
      
    # Prometheus-friendly labels for service discovery
    labels:
      - "prometheus.enable=true"
      - "prometheus.port=8758"
      - "prometheus.path=/metrics"
      - "netring.location=US1"
      - "netring.role=member"
      - "netring.version=v1.1.8"
      
    healthcheck:
      test: ["CMD", "sh", "-c", "wget -qO- http://localhost:8758/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
      
    restart: unless-stopped
    
    # Run without config file - uses environment variables only!
    command: ["python", "member/main.py"]
    
    # Optional: Resource limits for production
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    
    # Network configuration
    networks:
      - netring
    
    # Optional: Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  netring:
    name: netring
    driver: bridge