version: "3.8"

services:
  netring-member:
    image: harbor.gss.consilio.com/public/library/netring-member:v1.1.8
    container_name: netring-member
    ports:
      - "8757:8757"               # exposes http://localhost:8757 (fixed port)
    environment:
      # Member configuration via environment variables (no config file needed!)
      - NETRING_LOCATION=LNT
      - NETRING_REGISTRY_URL=https://netring-reg.gss.consilio.com
      - NETRING_POLL_INTERVAL=30
      - NETRING_CHECK_INTERVAL=60
      - NETRING_HEARTBEAT_INTERVAL=45
      - NETRING_TCP_TIMEOUT=5
      - NETRING_HTTP_TIMEOUT=10
      - NETRING_HTTP_ENDPOINTS=/health,/metrics
      - NETRING_SERVER_HOST=0.0.0.0
      - NETRING_SERVER_PORT=8757
      
      # Enhanced testing configuration (new in v1.1.8)
      - NETRING_BANDWIDTH_TEST_INTERVAL=300    # 5 minutes
      - NETRING_TRACEROUTE_INTERVAL=600        # 10 minutes  
      - NETRING_BANDWIDTH_TEST_SIZE_MB=1       # 1MB test size
      
      # Auto-detected host IP will be injected here
      - HOST_IP=${HOST_IP}
      # Reduce HTTP access log noise (optional)
      - PYTHONUNBUFFERED=1
    # optional: Prometheus-friendly labels if you're using docker_sd discovery
    labels:
      - "prometheus.enable=true"
      - "prometheus.port=8757"
      - "prometheus.path=/metrics"
    healthcheck:
      test: ["CMD", "sh", "-c", "wget -qO- http://localhost:8757/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    # Graceful shutdown - give container time to deregister from registry
    stop_grace_period: 30s
    # Run without config file - uses environment variables only!
    command: ["python", "member/main.py"]
    # Resource limits (for newer Docker Compose only)
    # deploy:
    #   resources:
    #     limits:
    #       memory: 256M
    #       cpus: '0.5'
    # No config file mount needed!
    # volumes:
    #   - ./member.yml:/app/config/member.yaml:ro
    networks:
      - netring

networks:
  netring: {}
