registry:
  redis:
    host: "localhost"
    port: 6379
    db: 0
    password: null
  
  server:
    host: "0.0.0.0"
    port: 8756
    
  member_ttl: 300  # seconds before a member is considered dead
  cleanup_interval: 60  # how often to clean up dead members