registry:
  redis:
    host: "redis"  # Use Docker service name
    port: 6379
    db: 0
    password: null
  
  server:
    host: "0.0.0.0"
    port: 8756
    
  member_ttl: 300  # seconds before a member is considered dead
  cleanup_interval: 60  # how often to clean up dead members
  
  # Expected members configuration (optional feature)
  expected_members:
    config_file: "config/expected-members.yaml"
    enable_missing_detection: false  # Set to true to enable missing members alerts
    missing_check_interval: 60       # how often to check for missing members